// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV6WjFpUiUMxl9ACOENr-2y-iC1epVCLc',
    appId: '1:222595027065:web:9ed7308fbea4cfe9b384a8',
    messagingSenderId: '222595027065',
    projectId: 'bengaluru-townsquare',
    authDomain: 'bengaluru-townsquare.firebaseapp.com',
    storageBucket: 'bengaluru-townsquare.appspot.com',
    measurementId: 'G-GPZP7EMT5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNvUxe3acI27uG1iB9VoFrS8ltJWOsOk0',
    appId: '1:222595027065:android:c62c083757fbc750b384a8',
    messagingSenderId: '222595027065',
    projectId: 'bengaluru-townsquare',
    storageBucket: 'bengaluru-townsquare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA47aTQGMOnyUWjJJUO9GtiyZjSASMBLbY',
    appId: '1:222595027065:ios:55897c2d39efc463b384a8',
    messagingSenderId: '222595027065',
    projectId: 'bengaluru-townsquare',
    storageBucket: 'bengaluru-townsquare.appspot.com',
    iosBundleId: 'com.example.bengaluruTownsquare',
  );
}
